# Generated by Django 5.1.7 on 2025-03-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
